import fs from 'fs/promises';
import path from 'path';
import { ensureValidName, exists, writeFile } from '../utils/fs.js';
import { toPascalCase } from '../utils/scaffolds.js';

const SUPPORTED_TYPES = new Set(['view', 'controller', 'model', 'validator', 'dto', 'service', 'subscriber', 'route']);

function normalizeType(type) {
  if (type === 'controller') {
    return 'view';
  }
  if (type === 'dto') {
    return 'validator';
  }
  return type;
}

function assertType(type) {
  if (!SUPPORTED_TYPES.has(type)) {
    throw new Error(`Unsupported generate type \"${type}\". Supported: ${Array.from(SUPPORTED_TYPES).join(', ')}`);
  }
}

async function assertProjectRoot(projectRoot) {
  const hasSingleSettings = await exists(path.join(projectRoot, 'settings.js'));
  const hasLegacySettings = (await exists(path.join(projectRoot, 'settings', 'index.js')))
    || (await exists(path.join(projectRoot, 'settings', 'apps.js')));

  if (!hasSingleSettings && !hasLegacySettings) {
    throw new Error('Not an AegisNode project root: missing settings.js');
  }
}

async function assertAppRoot(projectRoot, appName) {
  const appRoot = path.join(projectRoot, 'apps', appName);
  if (!(await exists(appRoot))) {
    throw new Error(`App \"${appName}\" does not exist. Create it first with: aegisnode createapp ${appName}`);
  }
  return appRoot;
}

function renderView(name, appName) {
  const className = `${toPascalCase(name)}View`;
  return `class ${className} {
  static index(req, res) {
    res.json({
      app: '${appName}',
      view: '${name}',
      message: 'Generated by AegisNode',
    });
  }
}

export default ${className};
`;
}

function renderModel(name) {
  const className = `${toPascalCase(name)}Model`;
  return `class ${className} {
  constructor({ dbClient }) {
    this.dbClient = dbClient;
  }
}

export default ${className};
`;
}

function renderService(name) {
  const className = `${toPascalCase(name)}Service`;
  return `class ${className} {
  constructor({ models }) {
    this.models = models;
  }
}

export default ${className};
`;
}

function renderValidator(name) {
  const className = `${toPascalCase(name)}Validator`;
  return `class ${className} {
  normalize(payload) {
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
      const error = new Error('Payload must be an object.');
      error.statusCode = 400;
      throw error;
    }
    return payload;
  }
}

export default ${className};
`;
}

function renderSubscriber(name, appName) {
  const fnName = `register${toPascalCase(name)}Subscriber`;
  return `export default function ${fnName}({ events, logger }) {
  events.subscribe('app.booted', ({ appName: mountedApp }) => {
    if (mountedApp !== '${appName}') {
      return;
    }

    logger.debug('[subscriber:${name}] ${appName} booted');
  });
}
`;
}

async function getAppRoutesFile(appRoot) {
  const primary = path.join(appRoot, 'routes.js');
  if (await exists(primary)) {
    return primary;
  }

  const legacy = path.join(appRoot, 'routes', 'index.js');
  if (await exists(legacy)) {
    return legacy;
  }

  throw new Error(`Missing app routes file in ${appRoot}. Expected routes.js or routes/index.js`);
}

async function appendRouteToApp({ appRoot, routeName }) {
  const routesFile = await getAppRoutesFile(appRoot);
  const usesFlatRoutesFile = path.basename(routesFile) === 'routes.js';
  const flatViewPath = path.join(appRoot, `${routeName}.view.js`);
  const nestedViewPath = path.join(appRoot, 'views', `${routeName}.view.js`);

  let importPath = null;
  if (await exists(flatViewPath)) {
    importPath = usesFlatRoutesFile
      ? `./${routeName}.view.js`
      : `../${routeName}.view.js`;
  } else if (await exists(nestedViewPath)) {
    importPath = usesFlatRoutesFile
      ? `./views/${routeName}.view.js`
      : `../views/${routeName}.view.js`;
  } else {
    throw new Error(`Missing view for route generation: ${flatViewPath} (or ${nestedViewPath}). Create it first with generate view ${routeName}.`);
  }

  const viewClass = `${toPascalCase(routeName)}View`;
  const importLine = `import ${viewClass} from '${importPath}';`;
  const routeLine = `    route.get('/${routeName}', ${viewClass}.index);`;

  let content = await fs.readFile(routesFile, 'utf8');

  if (!content.includes(importLine)) {
    const lines = content.split('\n');
    let lastImportIndex = -1;
    for (let i = 0; i < lines.length; i += 1) {
      if (lines[i].startsWith('import ')) {
        lastImportIndex = i;
      }
    }

    if (lastImportIndex >= 0) {
      lines.splice(lastImportIndex + 1, 0, importLine);
    } else {
      lines.unshift(importLine);
    }
    content = lines.join('\n');
  }

  if (!content.includes(routeLine)) {
    const markerEnd = '    // AEGIS_APP_EXTRA_ROUTES_END';
    if (content.includes(markerEnd)) {
      content = content.replace(markerEnd, `${routeLine}\n${markerEnd}`);
    } else {
      const lines = content.split('\n');
      let closeIndex = -1;
      for (let i = lines.length - 1; i >= 0; i -= 1) {
        if (lines[i].trim() === '},' || lines[i].trim() === '})' || lines[i].trim() === '};') {
          closeIndex = i;
          break;
        }
      }

      if (closeIndex < 0) {
        throw new Error(`Cannot auto-wire route in ${routesFile}. Could not find object block end.`);
      }

      lines.splice(closeIndex, 0, routeLine);
      content = lines.join('\n');
    }
  }

  await writeFile(routesFile, content);
  return routesFile;
}

function resolveTarget(appRoot, type, name) {
  switch (type) {
    case 'view':
      return path.join(appRoot, `${name}.view.js`);
    case 'model':
      return path.join(appRoot, `${name}.model.js`);
    case 'service':
      return path.join(appRoot, `${name}.service.js`);
    case 'validator':
      return path.join(appRoot, `${name}.validator.js`);
    case 'subscriber':
      return path.join(appRoot, `${name}.subscriber.js`);
    default:
      throw new Error(`Unsupported type: ${type}`);
  }
}

function renderContent(type, name, appName) {
  switch (type) {
    case 'view':
      return renderView(name, appName);
    case 'model':
      return renderModel(name);
    case 'service':
      return renderService(name);
    case 'validator':
      return renderValidator(name);
    case 'subscriber':
      return renderSubscriber(name, appName);
    default:
      throw new Error(`Unsupported type: ${type}`);
  }
}

export async function generateArtifact({ type, name, appName, projectRoot }) {
  if (!type) {
    throw new Error('Missing generate type. Usage: aegisnode generate <type> <name> --app <app-name>');
  }

  if (!name) {
    throw new Error('Missing artifact name. Usage: aegisnode generate <type> <name> --app <app-name>');
  }

  if (!appName) {
    throw new Error('Missing app name. Use --app <app-name>');
  }

  assertType(type);
  const normalizedType = normalizeType(type);
  ensureValidName(name, normalizedType);
  ensureValidName(appName, 'app');

  const resolvedRoot = path.resolve(projectRoot);
  await assertProjectRoot(resolvedRoot);
  const appRoot = await assertAppRoot(resolvedRoot, appName);

  if (normalizedType === 'route') {
    const routesFile = await appendRouteToApp({ appRoot, routeName: name });
    console.log(`Generated route /${name} in ${routesFile}`);
    return;
  }

  const targetFile = resolveTarget(appRoot, normalizedType, name);
  if (await exists(targetFile)) {
    throw new Error(`File already exists: ${targetFile}`);
  }

  await writeFile(targetFile, renderContent(normalizedType, name, appName));

  console.log(`Generated ${normalizedType}: ${targetFile}`);
}
